# Render deployment configuration
services:
  # Backend service
  - type: web
    name: real-estate-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: VAPI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com
      - key: NODE_ENV
        value: production

  # Frontend service
  - type: static
    name: real-estate-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com
      - key: REACT_APP_VAPI_PUBLIC_KEY
        sync: false
      - key: REACT_APP_VAPI_ASSISTANT_ID
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html