spec:
  name: real-estate-voice-app
  region: nyc
  services:
  - name: backend
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/your-repo-name
    source_dir: /backend
    build_command: npm install
    run_command: node src/index.js
    envs:
    - key: PORT
      value: "8080"
    - key: NODE_ENV
      value: "production"
    - key: VAPI_API_KEY
      type: SECRET
    - key: FRONTEND_URL
      value: "${APP_URL}"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: frontend
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/your-repo-name
    source_dir: /frontend
    build_command: npm install && npm run build
    envs:
    - key: REACT_APP_API_URL
      value: "${backend.PUBLIC_URL}"
    - key: REACT_APP_VAPI_PUBLIC_KEY
      type: SECRET
    - key: REACT_APP_VAPI_ASSISTANT_ID
      type: SECRET